const fs = require('fs');
const file = 'backend/src/services/agent2RiskAnalyst.js';
let content = fs.readFileSync(file, 'utf8');

const judgePrompt = `
const JUDGE_SYSTEM_PROMPT = \`
Role: Chief Compliance Arbitrator & Legal Quality Control Engine (Indian Jurisprudence).
Task: Audit the initial Risk Analysis generated by the Base Analyst against the Original Wording of the contract clause and the provided Global Contract Context.

You are an adversarial layer designed to eliminate two critical systemic errors:
1. FALSE POSITIVES (Over-Sensitivity): If the Base Analyst assigned a HIGH/CRITICAL risk score to a clause that explicitly contains saving or protective qualifiers (e.g., "conforming strictly to state Shops & Establishments frameworks", "mutual consensus of both parties", "limited strictly to in-scope working hours"), you must REJECT the score and downscale it to LOW RISK (1-2) or safe MEDIUM RISK, wiping any hallucinated penalty commentary.
2. FALSE NEGATIVES (Overlooked Traps): If the Base Analyst missed an explicit predatory mechanism (e.g., contracting out of Section 19(4) of the Copyright Act, unilateral sole arbitrator selection, shifting business risks via Section 74 salary escrow forfeitures), you must REJECT its lenient assessment, escalate the rating to HIGH/CRITICAL, and insert the precise statutory warning block.

You must output a strictly validated JSON array matching the exact structure of the input, with corrected risk ratings, scores, audit notes, and citations based on your verification. No conversational wrappers.
\`;
`;

content = content.replace('const ALLOWED_ACT_KEYS', judgePrompt + '\nconst ALLOWED_ACT_KEYS');

const newRunAgent2 = `
/**
 * Executes the Adversarial Reflection pass over the Base Analyst's outputs
 */
async function runAdversarialJudge(globalContext, clauseText, baseAnalysisJson) {
  const prompt = \`
  === GLOBAL CONTRACT CONTEXT ===
  \${JSON.stringify(globalContext || {}, null, 2)}
  
  === ORIGINAL CLAUSE TEXT ===
  "\${clauseText}"
  
  === BASE ANALYST DRAFT REPORT ===
  \${JSON.stringify(baseAnalysisJson, null, 2)}
  
  Execute your adversarial quality audit now. Output the final, verified JSON object.
  \`;

  try {
    const rawOutput = await require('./aiClient').callLLM({
      systemPrompt: JUDGE_SYSTEM_PROMPT,
      userContent: prompt,
      jsonMode: true,
      temperature: 0.1, // Kept low for deterministic legal evaluation
      maxTokens: 4096,
    });
    if (rawOutput && Array.isArray(rawOutput.results)) return rawOutput.results[0] || rawOutput;
    if (Array.isArray(rawOutput)) return rawOutput[0] || baseAnalysisJson;
    return rawOutput || baseAnalysisJson;
  } catch (err) {
    console.error('[Adversarial Judge] Failed reflection pass, falling back to base:', err.message);
    return baseAnalysisJson;
  }
}

async function runAgent2RiskAnalyst(clausesBatch, globalContext) {
  const formattedBatch = clausesBatch.map((c) => {
    if (!globalContext) return c;
    const globalPreamble = \`
======================================================================
[V3 CRITICAL ARCHITECTURAL RUNTIME CONTEXT - DO NOT BYPASS]
The following parameters have been extracted from the root header of this document. 
Utilize these explicit definitions to analyze the semantic intent of the active clause below.

Governing Framework: \${globalContext.metadata?.governingLaw || "Not Explicitly Defined"}
Corporate Employer: \${globalContext.metadata?.employerName || "Not Explicitly Defined"}
Target Designation: \${globalContext.metadata?.employeeDesignation || "Not Explicitly Defined"}

Global Definitions Mapping Matrix:
\${JSON.stringify(globalContext.globalDefinitions || {}, null, 2)}
======================================================================

[ACTIVE TARGET EVALUATION CLAUSE TEXT]:
\`;
    return {
      ...c,
      text: globalPreamble + c.text
    };
  });

  const userContent = JSON.stringify({ clauses: formattedBatch });

  const resp = await require('./aiClient').callLLM({
    systemPrompt: SYSTEM_PROMPT,
    userContent,
    jsonMode: true,
    temperature: 0.2,
    maxTokens: 6144,
  });

  const clauseTextMap = {};
  for (const c of clausesBatch) {
    clauseTextMap[c.id] = c.text;
  }

  const baseResults = (resp.results || []).filter((r) => r && r.id && mongoose.Types.ObjectId.isValid(r.id));
  
  // Step 2: Immediate Adversarial Reflection Audit Loop (Agent 2.5)
  const finalResults = await Promise.all(
    baseResults.map(async (baseAnalysis) => {
      const originalText = clauseTextMap[baseAnalysis.id] || '';
      const verifiedAnalysis = await runAdversarialJudge(globalContext, originalText, baseAnalysis);
      
      const risk_score = verifiedAnalysis.risk_score !== undefined ? verifiedAnalysis.risk_score : (verifiedAnalysis.score !== undefined ? verifiedAnalysis.score : baseAnalysis.risk_score);
      const risk_level = verifiedAnalysis.risk_level || verifiedAnalysis.riskRating || baseAnalysis.risk_level;
      const risk_reasons = verifiedAnalysis.risk_reasons || (verifiedAnalysis.auditNote ? [verifiedAnalysis.auditNote] : baseAnalysis.risk_reasons);
      const possible_law_references = verifiedAnalysis.possible_law_references || verifiedAnalysis.citations || baseAnalysis.possible_law_references;
      
      const score = clampScore(risk_score);
      let level = RISK_LEVELS.includes(risk_level ? risk_level.toLowerCase() : '') ? risk_level.toLowerCase() : 'medium';
      if (score <= 5 && level !== 'low') level = 'low';
      
      return {
        id: baseAnalysis.id,
        risk_level: level,
        risk_score: score,
        risk_reasons: Array.isArray(risk_reasons) ? risk_reasons : [],
        possible_law_references: sanitiseLawRefs(possible_law_references),
      };
    })
  );

  return finalResults;
}
`;

const regex = /async function runAgent2RiskAnalyst[\s\S]*?function clampScore/m;
content = content.replace(regex, newRunAgent2 + '\nfunction clampScore');

// Export runAdversarialJudge for testing
if (!content.includes('runAdversarialJudge')) {
    console.log("Error: runAdversarialJudge not found in content");
} else {
    content = content.replace('module.exports = { runAgent2RiskAnalyst, analyseRisksForContract };', 'module.exports = { runAgent2RiskAnalyst, analyseRisksForContract, runAdversarialJudge };');
    fs.writeFileSync(file, content);
    console.log("Successfully updated agent2RiskAnalyst.js");
}
